Repository ABCxFF/diepcustom, pull requests merged in 2022-11, with the labels that each got.

#55 Minor patches(#44,#49,#50,#2, #4)
  src/Client.ts
  src/Coder/Writer.ts
  src/Const/DevTankDefinitions.ts
  src/Entity/AI.ts
  src/Entity/Boss/AbstractBoss.ts
  src/Entity/Misc/Dominator.ts
  src/Entity/Object.ts
  src/Native/Camera.ts
  src/config.ts
Labels: inaccuracy

#57 Client Feature: Global Game Object
  client/loader.js
Labels: readability, misc

#66 patch some mothership stuff
  src/Client.ts
  src/Const/Enums.ts
  src/Entity/AI.ts
  src/Entity/Misc/Mothership.ts
  src/Gamemodes/Mothership.ts
  src/Native/Arena.ts
  src/index.ts
Labels: inaccuracy, readability

#67 fix domination "peaceful" bases
  src/Entity/Object.ts
Labels: inaccuracy

#70 Patch up mothership
  src/Const/Enums.ts
  src/Entity/Misc/Mothership.ts
  src/Entity/Misc/TeamEntity.ts
  src/Entity/Tank/Barrel.ts
  src/Gamemodes/Mothership.ts
Labels: inaccuracy

#69 feat: barrel addons and "swarm"
  src/Const/DevTankDefinitions.ts
  src/Const/TankDefinitions.ts
  src/Entity/Tank/Addons.ts
  src/Entity/Tank/Barrel.ts
  src/Entity/Tank/BarrelAddons.ts
  src/Entity/Tank/Projectile/Drone.ts
  src/Entity/Tank/Projectile/Swarm.ts
  src/Entity/Tank/TankBody.ts
Labels: readability, suggestion, misc

#85 Minor changes
  src/Const/DevTankDefinitions.ts
  src/Entity/Boss/AbstractBoss.ts
  src/Entity/Tank/AutoTurret.ts
  src/Entity/Tank/Projectile/Bullet.ts
  src/config.ts
Labels: misc

#92 patches
  src/Client.ts
  src/Const/DevTankDefinitions.ts
  src/Const/TankDefinitions.ts
  src/Entity/AI.ts
  src/Entity/Boss/Defender.ts
  src/Entity/Boss/Summoner.ts
  src/Entity/Misc/Dominator.ts
  src/Entity/Misc/Mothership.ts
  src/Entity/Object.ts
  src/Entity/Shape/AbstractShape.ts
  src/Entity/Shape/Crasher.ts
  src/Entity/Tank/Addons.ts
  src/Entity/Tank/AutoTurret.ts
  src/Entity/Tank/Barrel.ts
  src/Entity/Tank/Projectile/Drone.ts
  src/Entity/Tank/Projectile/NecromancerSquare.ts
  src/Entity/Tank/Projectile/Trap.ts
  src/Entity/Tank/TankBody.ts
  src/Game.ts
  src/Gamemodes/Domination.ts
  src/Gamemodes/Misc/Ball.ts
  src/Gamemodes/Misc/Testing.ts
  src/Gamemodes/Mothership.ts
  src/Gamemodes/Sandbox.ts
  src/Gamemodes/Team2.ts
  src/Gamemodes/Team4.ts
  src/Native/Arena.ts
  src/config.ts
  src/index.ts
  src/util.ts
Labels: inaccuracy
