Repository ABCxFF/diepcustom, pull requests merged in 2022-10, with the labels that each got.

#11 fix issue #7
  src/Entity/Object.ts
Labels: inaccuracy

#16 Patch/ip limit #15
  src/Client.ts
  src/Game.ts
  src/config.ts
Labels: suggestion

#17 update grammatical semantics
  README.md
Labels: readability

#21 fix(#13): entities velocity gets halfed when dying
  src/Entity/Object.ts
  src/Entity/Tank/Projectile/Bullet.ts
Labels: inaccuracy

#22 fix contributing.md
  CONTRIBUTING.md
Labels: readability

#24 fix(#23): add cheatflag when dev cheats used, make it persist
  src/Client.ts
Labels: inaccuracy

#28 fix(#27): default dev password to sha256(''), so everyone is dev by default
  src/Client.ts
  src/config.ts
Labels: critical, misc

#32 Cleanup + minor rerouting
  src/Client.ts
  src/Entity/Boss/AbstractBoss.ts
  src/Entity/Tank/Addons.ts
  src/Native/Arena.ts
  src/Native/Camera.ts
  src/config.ts
  src/index.ts
Labels: misc
